name: Submodule Sync
on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch: ~

jobs:
  submodule-sync:
    name: Submodule Sync
    runs-on: ubuntu-latest
    steps:
      - name: Submodule Sync
        uses: mheap/submodule-sync-action@v1
        with:
          path: utils/
          ref: master
          pr_branch: bump-utils-version
          target_branch: dev
